version: "3"
services:
  db:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: k8s_proj
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
  db.gui:
    image: adminer
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
    labels:
      com.list.name: Adminer
      com.list.sort: "2"
      com.list.link.endpoint: Browse database|/?pgsql=db&username=root&db=k8s_proj&ns=public
  container-list:
    image: awesome1888/container-list
    expose:
      - "2000"
    ports:
      - "2000:2000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - PORT=2000
  back:
    image: "back:dev"
    build:
      context: ../app.back/
      dockerfile: infra/development.dockerfile
    expose:
      - "4000"
      - "4001"
    ports:
      - "4000:4000"
      - "4001:4001"
    depends_on: []
    volumes:
      - "../app.back/:/app/"
    environment:
      - NODE_ENV=development
      - DEBUG=gql.*
      - DEBUG_COLORS=1
      - DEBUG_HIDE_DATE=1
      - NETWORK__PORT=4000
      - NETWORK__PORT__DEBUGGER=4001
      - NETWORK__CORS=
      - "DATABASE__URL=postgres://root:123@db:5432/k8s_proj"
    labels:
      com.list.name: Back
  front:
    image: "front:dev"
    build:
      context: ../app.front/
      dockerfile: infra/development.dockerfile
    ports:
      - "3010:3010"
      - "3001:3001"
      - "3000:3000"
    depends_on: []
    volumes:
      - "../app.front/:/app/"
    environment:
      - NODE_ENV=development
      - DEBUG_COLORS=1
      - DEBUG_HIDE_DATE=1
      - NETWORK__PORT=3000
      - NETWORK__PORT__HMR=3001
      - NETWORK__PORT__BUNDLE_ANALYSER=3010
      - NETWORK__CORS=
      - TEMPLATE__PATH=./index.html
      - "API__URL=http://localhost:3000"
    labels:
      com.list.name: Front
      com.list.link.analyzer: "Bundle analyzer|http://localhost:3010"
